spring.application.name=mixify

# H2 in-memory adatbázis beállításai
spring.datasource.url=jdbc:h2:mem:mixifydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hogy a táblák automatikusan létrejöjjenek a Java modellek alapján
spring.jpa.hibernate.ddl-auto=update

# H2 webes konzol bekapcsolása
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console